Repository SanjayMarreddi/Facial-Expression-Recognition-Classifier-Model, pull requests merged in 2021-02, with the labels that each got.

#41 Trained the model for avengers
  Facial_Recognition_Models/Using_Standard_Libraries/Basic_Avengers_Recognition/Readme.md
  Facial_Recognition_Models/Using_Standard_Libraries/Basic_Avengers_Recognition/data_img/captain_america.jpeg
  Facial_Recognition_Models/Using_Standard_Libraries/Basic_Avengers_Recognition/data_img/hulk.jpg
  Facial_Recognition_Models/Using_Standard_Libraries/Basic_Avengers_Recognition/data_img/thor.jpeg
  Facial_Recognition_Models/Using_Standard_Libraries/Basic_Avengers_Recognition/data_img/tony.jpg
  Facial_Recognition_Models/Using_Standard_Libraries/Basic_Avengers_Recognition/requirements.txt
  Facial_Recognition_Models/Using_Standard_Libraries/Basic_Avengers_Recognition/script.py
Labels: DWOC, Level-4

#40 Enhance the Frontend & Make it more Attractive
  static/style.css
  static/undraw_the_search_s0xf (1) 1.svg
  templates/ManualUpload.html
  templates/NoDetection.html
  templates/RealTime.html
  templates/Start.html
  templates/Visual.html
Labels: DWOC, Level-4, enhancement

#45 Added activity suggestion
  main.py
  static/images/Angry/img.jpg
  static/images/Disgust/img.jpg
  static/images/Fear/img.jpg
  static/images/Happy/img.jpg
  static/images/Neutral/img.jpg
  static/images/Sad/img.jpg
  static/images/Surprise/img.jpg
  templates/Visual.html
Labels: DWOC, Level-4, enhancement

#46 Update README.md
  README.md
Labels: DWOC, Level-1

#50 Contributors Table
  README.md
Labels: DWOC, Level-2

#54 This is the UI (HTML + CSS) part of CNN model for predicting Indian actor
  Facial_Recognition_Models/Using_CNN/Indian_Celebrity_Recognition/static/css/main.css
  Facial_Recognition_Models/Using_CNN/Indian_Celebrity_Recognition/static/js/main.js
  Facial_Recognition_Models/Using_CNN/Indian_Celebrity_Recognition/templates/base.html
  Facial_Recognition_Models/Using_CNN/Indian_Celebrity_Recognition/templates/index.jpg
Labels: DWOC, Level-4

#56 Update README.md
  Facial_Recognition_Models/Using_CNN/Indian_Celebrity_Recognition/README.md
Labels: DWOC, Level-1
